// Portal del coach (asesor.html): acceso, CRM, borradores, vista previa y envío.
const T = require('./sitio.js'); const { ok } = T;
const fs = require('fs');
const resp = (j, status = 200, extra = {}) => Object.assign({ ok: status < 400, status, json: async () => j, headers: { get: () => null } }, extra);
(async () => {
  const data = JSON.parse(fs.readFileSync(T.RAIZ + '/data.json', 'utf8'));
  const crmEbs = data.filter(p => p.municipio === 'Zapopan' && p.operacion === 'VENTA' && p.tipo === 'casa').slice(0, 2).map(p => p.eb);
  const llamadas = [];
  const interceptar = (u, op) => {
    if (!u.includes('/api/asesor/')) return null;
    const ruta = u.split('/api/asesor')[1]; const b = JSON.parse(op.body || '{}'); llamadas.push([ruta, b]);
    if (ruta === '/usuarios') return resp({ ok: true, usuarios: [{ usuario: 'ubaldo', nombre: 'Ubaldo Mendez', activo: true }, { usuario: 'paola', nombre: 'Paola Valencia', activo: false }] });
    if (ruta === '/login') return b.clave === 'buena' ? resp({ ok: true, token: 'TOK', nombre: 'Ubaldo Mendez' }) : resp({ ok: false, error: 'Usuario o contraseña incorrectos.' }, 401);
    if (ruta === '/cliente') return resp({ ok: true, encontrado: true, nombre: 'María López', folio: 'AM-0142', vendedor: 'Ubaldo Mendez', operacion: 'VENTA', propiedades: crmEbs, contexto: 'Cliente: busco casa' });
    if (ruta === '/propuesta' && b.modo === 'vista') return resp({}, 200, { blob: async () => ({}), headers: { get: () => null } });
    if (ruta === '/propuesta' && b.modo === 'enviar') return resp({ ok: true, cliente_ok: true, via: 'archivo', coach_ok: true, liga: 'https://x' });
    return resp({ ok: false }, 404);
  };
  const errores = [];
  const w = await T.abrir('asesor.html', '', errores, interceptar);
  w.URL.createObjectURL = () => 'blob:prueba'; w.URL.revokeObjectURL = () => {};
  w.confirm = () => true; w.alert = () => {};
  const d = w.document, $ = id => d.getElementById(id);
  const opciones = [...$('asUsuario').options].map(o => o.textContent);
  ok(opciones.includes('Ubaldo Mendez') && !opciones.includes('Paola Valencia'), 'solo aparecen los coaches que tienen contraseña');
  ok(d.querySelector('meta[name="robots"]').content.includes('noindex'), 'la página no se indexa en buscadores');
  $('asUsuario').value = 'ubaldo'; $('asClave').value = 'mala'; $('asEntrar').click(); await T.espera(100);
  ok(!$('asLogin').hidden && /incorrect/.test($('asLoginMsg').textContent), 'contraseña incorrecta: no entra y lo explica');
  $('asClave').value = 'buena'; $('asEntrar').click(); await T.espera(800);
  ok($('asLogin').hidden && !$('asApp').hidden && /Ubaldo/.test($('asSesion').textContent), 'con la contraseña correcta entra y muestra su nombre');
  $('asWa').value = '3324970007'; $('asBuscar').click(); await T.espera(200);
  ok($('asNombre').value === 'María López' && $('asFolio').value === 'AM-0142', 'trae nombre y folio del CRM');
  const tarjetas = d.querySelectorAll('.as-prop');
  ok(tarjetas.length === crmEbs.length, `agrega solas las ${crmEbs.length} propiedades que el cliente vio`);
  const res = tarjetas[0].querySelector('textarea[data-campo="resumen"]').value, ven = tarjetas[0].querySelector('textarea[data-campo="ventajas"]').value;
  ok(/en venta en/.test(res) && /Zapopan/.test(res), 'propone un resumen con los datos reales de la ficha: ' + res.slice(0, 70));
  ok(ven.split('\n').filter(Boolean).length >= 1 && !/alberca|gimnasio|seguridad 24/i.test(ven), 'propone ventajas sin inventar amenidades');
  $('asBuscarEB').value = data[100].eb; $('asBuscarEB').dispatchEvent(new w.Event('input')); await T.espera(50);
  d.querySelector('#asSugerencias button[data-k]').click(); await T.espera(50);
  ok(d.querySelectorAll('.as-prop').length === crmEbs.length + 1, 'agrega una propiedad por clave EB');
  d.querySelectorAll('.as-prop')[2].querySelector('button[data-acc="subir"]').click(); await T.espera(20);
  ok(d.querySelectorAll('.as-prop')[1].textContent.includes(data[100].eb), 'reordena las propiedades');
  const ta = d.querySelector('.as-prop textarea[data-campo="ventajas"]'); ta.value = 'Cerca de escuelas\n- A 5 min de Periférico'; ta.dispatchEvent(new w.Event('input', { bubbles: true }));
  $('asNota').value = 'buscas cerca de escuelas';
  $('asVista').click(); await T.espera(200);
  const vista = llamadas.find(l => l[0] === '/propuesta' && l[1].modo === 'vista');
  ok(vista && vista[1].token === 'TOK' && vista[1].propiedades.length === 3 && vista[1].propiedades[0].ventajas[0] === 'Cerca de escuelas', 'la vista previa manda token, propiedades y las ventajas editadas');
  ok(d.querySelector('iframe.as-vista'), 'muestra el PDF dentro de la página');
  ok(vista[1].anexo === true && $('asAnexo').checked, 'por defecto anexa la ficha completa de cada propiedad');
  $('asEnviar').click(); await T.espera(200);
  ok(/Enviado/.test($('asMsg').textContent), 'al enviar confirma la entrega al cliente y la copia al coach');
  ok(errores.length === 0, 'sin errores de JavaScript' + (errores.length ? ' -> ' + errores.slice(0, 2).join(' | ') : ''));
  process.exit(T.fallas ? 1 : 0);
})();
